"use client";

import { useMovieFlow } from "@/app/hooks/useMovieFlow";

export function MovieApp() {
  const flow = useMovieFlow();
  const isAuthenticated = Boolean(flow.userEmail);

  return <main className="min-h-screen bg-[#070b12] text-white"><div className="mx-auto max-w-6xl px-4 py-10 sm:px-6"><header className="mb-8 flex flex-wrap items-center justify-between gap-4 border-b border-white/10 pb-4"><div><p className="text-xs uppercase tracking-[0.35em] text-cyan-300">Made in 冥途</p><h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">人生の最後に観る映画を、人生をかけて作る。</h1></div>{isAuthenticated ? <span className="rounded-full border border-emerald-400/30 bg-emerald-500/10 px-4 py-2 text-sm text-emerald-100">{flow.userEmail}</span> : <div className="flex flex-wrap gap-2"><input aria-label="メールアドレス" value={flow.email} onChange={(event) => flow.setEmail(event.target.value)} type="email" placeholder="メールアドレス" className="rounded-full border border-white/15 bg-slate-950 px-3 py-2 text-sm" /><input aria-label="パスワード" value={flow.password} onChange={(event) => flow.setPassword(event.target.value)} type="password" placeholder="パスワード" className="rounded-full border border-white/15 bg-slate-950 px-3 py-2 text-sm" /><button type="button" disabled={flow.busy === "auth" || !flow.email || !flow.password} onClick={() => flow.authenticate("signIn")} className="rounded-full bg-cyan-500 px-4 py-2 text-sm font-medium text-slate-950 disabled:opacity-50">ログイン</button><button type="button" disabled={flow.busy === "auth" || !flow.email || !flow.password} onClick={() => flow.authenticate("signUp")} className="px-2 text-sm text-cyan-200 underline disabled:opacity-50">新規登録</button></div>}</header>
    <section className="grid gap-6 lg:grid-cols-[1.2fr_0.8fr]"><div className="rounded-[32px] border border-white/10 bg-slate-900 p-6 sm:p-8"><p className="text-xs uppercase tracking-[0.3em] text-slate-400">偏愛探索</p><h2 className="mt-2 text-3xl font-semibold">記憶から、最後の映画をつくる</h2><label htmlFor="diary" className="mt-6 mb-2 block text-sm font-medium text-slate-200">今日の出来事</label><textarea id="diary" value={flow.diary} onChange={(event) => flow.setDiary(event.target.value)} rows={7} placeholder="思い出や繰り返し見返した場面を記録してください" className="w-full rounded-2xl border border-white/10 bg-slate-950 px-4 py-3 text-sm placeholder:text-slate-500" /><label className="mt-5 flex cursor-pointer items-center justify-center rounded-2xl border border-dashed border-cyan-400/40 bg-cyan-500/5 px-4 py-6 text-sm text-cyan-100"><input type="file" accept="image/*" multiple className="hidden" onChange={flow.addMedia} />写真を選択（最大12枚）</label><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-3">{flow.media.map((item) => <img key={item.id} src={item.previewUrl} alt={item.name} className="h-24 w-full rounded-xl object-cover" />)}</div><div className="mt-6 flex flex-wrap gap-3"><button type="button" onClick={flow.analyze} disabled={flow.busy !== null} className="rounded-full bg-white px-5 py-2.5 text-sm font-semibold text-slate-900 disabled:opacity-50">{flow.busy === "analysis" ? "分析中..." : "偏愛を分析"}</button><button type="button" onClick={flow.generate} disabled={!flow.obsession || flow.busy !== null} className="rounded-full border border-cyan-400/40 bg-cyan-500/10 px-5 py-2.5 text-sm font-semibold text-cyan-100 disabled:opacity-50">{flow.busy === "movie" ? "生成中..." : "映画を生成"}</button></div>{flow.message && <p role="status" className="mt-4 text-sm text-cyan-100">{flow.message}</p>}</div>
      <aside className="rounded-[32px] border border-white/10 bg-slate-900/80 p-6"><p className="text-xs uppercase tracking-[0.28em] text-slate-400">偏愛の定義</p><blockquote className="mt-4 border-l border-cyan-400/50 pl-4 text-lg leading-8 text-slate-100">「自分だけが心の奥で繰り返し見つめている瞬間が好きなのです。」</blockquote>{flow.obsession && <div className="mt-6 rounded-2xl border border-cyan-400/30 bg-cyan-500/10 p-4"><p className="text-xs text-cyan-200">分析結果</p><h3 className="mt-2 text-xl font-semibold">{flow.obsession.title}</h3><p className="mt-2 text-sm leading-6 text-slate-200">{flow.obsession.reason}</p></div>}</aside></section>
    <section className="mt-10 rounded-[32px] border border-white/10 bg-slate-900/80 p-6"><p className="text-xs uppercase tracking-[0.28em] text-slate-400">screening</p><h2 className="mt-2 text-2xl font-semibold">完成した映画</h2>{flow.movie?.videoUrl ? <video controls preload="metadata" className="mt-5 aspect-video w-full rounded-2xl bg-black" src={flow.movie.videoUrl}>生成した映画</video> : <div className="mt-5 flex aspect-video items-center justify-center rounded-2xl border border-white/10 bg-slate-950 text-sm text-slate-400">{flow.movie ? `生成状態: ${flow.movie.status}` : "映画を生成すると、ここで再生できます。"}</div>}{flow.movie?.movie?.scenes && <ol className="mt-5 grid gap-2 sm:grid-cols-3">{flow.movie.movie.scenes.map((scene) => <li key={scene.order} className="rounded-xl border border-white/10 bg-white/5 p-3 text-sm"><span className="text-cyan-200">{scene.order}. </span>{scene.source}<p className="mt-1 text-xs text-slate-300">{scene.narration}</p></li>)}</ol>}</section>
  </div></main>;
}
