"use client";

import type { ChangeEvent } from "react";
import type { MediaItem } from "@/app/types/last-screen";

type Props = { diary: string; onDiaryChange: (value: string) => void; media: MediaItem[]; onFileChange: (event: ChangeEvent<HTMLInputElement>) => void; signals: string[]; isAnalyzing: boolean; onAnalyze: () => void; isGenerating: boolean; canGenerate: boolean; onGenerate: () => void; message: string | null };

export function MemoryInputSection({ diary, onDiaryChange, media, onFileChange, signals, isAnalyzing, onAnalyze, isGenerating, canGenerate, onGenerate, message }: Props) {
  return <section className="grid gap-6 lg:grid-cols-[1.3fr_0.7fr]">
    <div className="rounded-[32px] border border-white/10 bg-gradient-to-br from-slate-900 via-slate-900 to-cyan-950/60 p-8 shadow-2xl shadow-black/40">
      <div className="mb-6 flex items-center justify-between"><div><p className="text-xs uppercase tracking-[0.3em] text-slate-400">偏愛探索</p><h2 className="mt-2 text-3xl font-semibold text-white">AIが、好きの粒度を見つける</h2></div><div className="rounded-full border border-emerald-400/30 bg-emerald-500/10 px-3 py-1 text-xs text-emerald-200">{media.length ? `${media.length}件のメディア` : "まだ未分析"}</div></div>
      <div className="grid gap-6 md:grid-cols-2"><div className="space-y-4"><div><label htmlFor="diary" className="mb-2 block text-sm font-medium text-slate-200">今日の出来事</label><textarea id="diary" value={diary} onChange={(event) => onDiaryChange(event.target.value)} rows={8} className="w-full rounded-2xl border border-white/10 bg-slate-950/70 px-4 py-3 text-sm text-slate-100 placeholder:text-slate-500 focus:border-cyan-400/70" placeholder="思い出や気分、繰り返し見返した場面を記録してください" /></div>
        <div><label className="mb-2 block text-sm font-medium text-slate-200">写真・動画をアップロード</label><label className="flex cursor-pointer items-center justify-center rounded-2xl border border-dashed border-cyan-400/30 bg-cyan-500/5 px-4 py-6 text-sm text-cyan-100"><input type="file" multiple accept="image/*,video/*" className="hidden" onChange={onFileChange} />画像や動画を選択</label><div className="mt-3 grid gap-2 sm:grid-cols-2">{media.length === 0 ? <span className="rounded-full border border-white/10 bg-white/5 px-2.5 py-1 text-xs text-slate-400 sm:col-span-2">まだアップロードされていません</span> : media.map((item) => <div key={item.id} className="overflow-hidden rounded-2xl border border-white/10 bg-slate-950/60">{item.type === "image" && item.previewUrl ? <img src={item.previewUrl} alt={item.name} className="h-24 w-full object-cover" /> : <div className="flex h-24 items-center justify-center bg-gradient-to-br from-violet-500/20 to-cyan-500/10 text-xs uppercase tracking-[0.2em] text-cyan-100">video</div>}<div className="truncate px-2.5 py-2 text-[11px] text-slate-200">{item.name}</div></div>)}</div></div></div>
        <div className="rounded-3xl border border-white/10 bg-black/20 p-4"><p className="mb-4 text-sm font-medium text-slate-300">AIによる検出の考え方</p><ul className="space-y-3 text-sm leading-6 text-slate-200">{signals.map((signal) => <li key={signal} className="rounded-2xl border border-white/10 bg-white/5 p-3">{signal}</li>)}</ul></div></div>
      <div className="mt-6 flex flex-wrap items-center gap-3"><button type="button" onClick={onAnalyze} disabled={isAnalyzing} className="rounded-full bg-white px-5 py-2.5 text-sm font-semibold text-slate-900 disabled:opacity-50">{isAnalyzing ? "分析中..." : "偏愛を分析"}</button><button type="button" onClick={onGenerate} disabled={isGenerating || !canGenerate} className="rounded-full border border-cyan-400/40 bg-cyan-500/10 px-5 py-2.5 text-sm font-semibold text-cyan-100 disabled:opacity-50">{isGenerating ? "生成を開始中..." : "映画を生成"}</button>{message && <p role="status" className="text-sm text-cyan-100">{message}</p>}</div>
    </div>
    <aside className="rounded-[32px] border border-white/10 bg-slate-900/80 p-6"><p className="text-xs uppercase tracking-[0.28em] text-slate-400">偏愛の定義</p><blockquote className="mt-4 border-l border-cyan-400/50 pl-4 text-lg leading-8 text-slate-100">「あなたは景色が好きなのではありません。自分だけが心の奥で繰り返し見つめている瞬間が好きなのです。」</blockquote><div className="mt-6 rounded-2xl border border-amber-300/30 bg-amber-500/10 p-4 text-sm leading-6 text-amber-100">このアプリは、あらかじめ決められた物語を表示するのではなく、ユーザーの写真や記録から偏愛を見つけて編集します。</div></aside>
  </section>;
}
